[package]
name = "marketplace"
version = "1.0.0"
authors = []
license = "MIT"

[addresses]
job_work_board = "0x7b4527999354aaac0936790b74a1ca53b04584b2ea2399eb819305f37799b1b7"
[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-stdlib" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/move-stdlib" }

[dev-addresses]
